/* =========================================================================
   VOZ — explicaciones locutadas "para todos los públicos" de los artículos
   estrella (los más importantes para las oposiciones). Para cada uno se
   explica, con lenguaje sencillo: qué significa, por qué importa, qué pasaría
   si no existiera y un ejemplo. El resto de artículos usan la explicación
   normal (opción B acordada con el usuario).

   Contenido original y divulgativo. No cita números de sentencias para no
   arriesgar datos inexactos: los ejemplos son situaciones ilustrativas.
   ========================================================================= */

const VOZ = {
  1: 'El artículo 1 es como la portada de las reglas de España. Dice que España es un país democrático donde el poder viene de las personas cuando votan, y que valen mucho la libertad, la justicia, la igualdad y el respeto a las distintas ideas. Importa porque marca cómo tiene que ser todo lo demás. Si no existiera, nadie sabría que mandan los ciudadanos y podría gobernar cualquiera sin que le eligiéramos. Por ejemplo, gracias a él elegimos con nuestro voto a quienes nos gobiernan.',
  2: 'El artículo 2 dice dos cosas a la vez: que España es una sola y no se puede partir, pero que sus territorios, como las comunidades autónomas, pueden gobernar en parte sus propios asuntos y ayudarse entre ellos. Importa porque une el país sin obligar a que todos sean idénticos. Si no existiera, o todo se mandaría desde un único sitio, o cada zona iría por su cuenta. Por ejemplo, por él tu comunidad puede tener su propio gobierno y seguir siendo España.',
  3: 'El artículo 3 habla de los idiomas. El castellano es la lengua oficial de todo el país: todos tenemos el deber de conocerlo y el derecho de usarlo. Además, otras lenguas, como el catalán, el gallego o el euskera, son oficiales en sus comunidades. Importa porque protege la lengua común y también las propias de cada zona. Si no existiera, algunas lenguas podrían perderse. Por ejemplo, gracias a él puedes estudiar en tu lengua propia en algunas comunidades.',
  9: 'El artículo 9 dice que nadie está por encima de las normas: ni tú, ni el Gobierno. Todos, incluso quienes mandan, tienen que cumplir la Constitución y las leyes. Una idea clave es que una ley nueva no puede castigarte por algo que hiciste antes, cuando todavía no estaba prohibido. Importa porque nos da seguridad. Si no existiera, los poderosos harían lo que quisieran. Por ejemplo, no pueden inventarse hoy un castigo por algo que hiciste el año pasado.',
  10: 'El artículo 10 habla de la dignidad, que significa que toda persona vale por el simple hecho de ser persona y merece respeto siempre. Es el cimiento del que nacen todos los demás derechos. Importa porque sin dignidad no habría derechos. Si no existiera, se podría tratar a la gente como si no valiera nada. Por ejemplo, por este artículo nadie puede humillarte ni tratarte como un objeto.',
  14: 'El artículo 14 dice que todos somos iguales ante la ley, sin que importe de dónde vienes, en qué crees, si eres niño o niña o cómo eres. Importa porque prohíbe tratar peor a alguien por ser diferente. Si no existiera, la ley podría dar más derechos a unos que a otros. Por ejemplo, gracias a él una niña y un niño tienen exactamente los mismos derechos.',
  15: 'El artículo 15 protege lo más importante: el derecho a la vida y a que nadie te haga daño ni te trate de forma cruel. Además, en España no existe la pena de muerte. Importa porque protege a las personas de la violencia, incluso la del Estado. Si no existiera, se podría castigar quitando la vida o maltratando. Por ejemplo, por él está totalmente prohibido torturar a alguien, pase lo que pase.',
  16: 'El artículo 16 habla de la libertad de pensar y de creer lo que quieras: puedes tener una religión, otra o ninguna, y nadie puede obligarte a decir en qué crees. Además, España no tiene una religión oficial del Estado. Importa porque protege tu libertad de conciencia. Si no existiera, te podrían obligar a creer algo. Por ejemplo, por él puedes ir a la iglesia, a la mezquita o a ningún sitio, y es solo decisión tuya.',
  17: 'El artículo 17 protege tu libertad: nadie puede detenerte sin motivo. Si te detiene la policía, no puede tenerte más de setenta y dos horas sin llevarte ante un juez, y debe explicarte por qué. Importa porque impide que te encierren sin control. Si no existiera, podrían meterte preso sin dar explicaciones. Por ejemplo, existe el habeas corpus, que obliga a llevar enseguida a un detenido ante el juez.',
  18: 'El artículo 18 protege tu intimidad: tus secretos, tu imagen y tu casa. Nadie puede entrar en tu vivienda ni leer tus mensajes sin permiso, salvo que lo autorice un juez o te pillen cometiendo un delito. Importa porque tu vida privada es tuya. Si no existiera, cualquiera podría espiarte o entrar en tu casa. Por ejemplo, la policía necesita una orden del juez para registrar tu vivienda.',
  20: 'El artículo 20 protege la libertad de expresión: puedes decir y escribir lo que piensas, y los periodistas pueden informar libremente. Además, nadie puede revisar y prohibir lo que vas a publicar antes de hacerlo. Importa porque sin ella no hay democracia de verdad. Si no existiera, el Gobierno podría callar a quien le critica. Por ejemplo, un periódico puede publicar una noticia que critique al Gobierno sin pedir permiso.',
  23: 'El artículo 23 dice que puedes participar en la política: votar y también presentarte a cargos públicos en igualdad con los demás. Importa porque recuerda que el poder es de los ciudadanos. Si no existiera, unos pocos decidirían por todos sin que pudiéramos elegir. Por ejemplo, por él puedes votar en las elecciones y, de mayor, incluso presentarte a ellas.',
  24: 'El artículo 24 garantiza que, si tienes un problema, puedes acudir a un juez que te escuche de forma justa y con abogado. Además, eres inocente hasta que se demuestre que hiciste algo malo. Importa porque protege a las personas frente a castigos injustos. Si no existiera, podrían condenarte sin pruebas ni defensa. Por ejemplo, nadie puede tratarte como culpable solo por sospechar de ti.',
  27: 'El artículo 27 habla del derecho a la educación: todos podéis estudiar, y la enseñanza básica es obligatoria y gratuita. Importa porque aprender abre puertas y forma ciudadanos libres. Si no existiera, solo estudiarían quienes pudieran pagarlo. Por ejemplo, por él tienes derecho a ir al colegio sin pagar en las etapas básicas.',
  53: 'El artículo 53 es como el guardián de los derechos: explica cómo se protegen de verdad. Los derechos más importantes solo se regulan por leyes especiales, y si te los vulneran puedes reclamar incluso ante el Tribunal Constitucional con el recurso de amparo. Importa porque un derecho sin protección no sirve de nada. Si no existiera, tus derechos serían solo palabras bonitas. Por ejemplo, si te vulneran un derecho fundamental, un tribunal puede defenderte.',
  56: 'El artículo 56 presenta al Rey, que es el Jefe del Estado y símbolo de la unión de España. El Rey representa al país, pero no gobierna como un rey de los cuentos: quien gobierna es el Gobierno elegido. Importa porque ordena quién representa a España. Si no existiera, no sabríamos quién simboliza al país por encima de la política. Por ejemplo, el Rey recibe a jefes de otros países en nombre de España.',
  62: 'El artículo 62 enumera lo que hace el Rey: firmar las leyes que aprueban las Cortes, convocar elecciones, proponer al presidente del Gobierno tras las votaciones y ser el jefe simbólico de las Fuerzas Armadas. Importa porque deja claras sus funciones, que casi siempre son de representación. Si no existiera, no estaría claro qué puede y qué no puede hacer el Rey. Por ejemplo, el Rey firma una ley, pero no puede inventarse las leyes él solo.',
  66: 'El artículo 66 presenta a las Cortes Generales, que son el Congreso y el Senado juntos. Representan al pueblo español y son quienes hacen las leyes. Importan porque son el corazón de la democracia: las eliges tú al votar. Si no existieran, nadie representaría a los ciudadanos al hacer las leyes. Por ejemplo, una ley nueva tiene que pasar por las Cortes antes de poder existir.',
  68: 'El artículo 68 habla del Congreso de los Diputados, elegido por todos los votantes. Sus miembros, los diputados, representan al pueblo y son clave para hacer las leyes y elegir al presidente del Gobierno. Importa porque es la cámara principal. Si no existiera, no tendríamos representantes elegidos directamente para las decisiones más importantes. Por ejemplo, tras unas elecciones, el Congreso vota quién será presidente.',
  99: 'El artículo 99 explica la investidura: cómo se elige al presidente del Gobierno. El Rey propone a un candidato, que presenta su plan al Congreso, y los diputados votan si le dan su confianza. Importa porque así el Gobierno nace del voto de tus representantes. Si no existiera, no sabríamos cómo se forma un Gobierno. Por ejemplo, tras las elecciones, el candidato tiene que convencer al Congreso para poder gobernar.',
  113: 'El artículo 113 habla de la moción de censura: es la forma en que el Congreso puede cambiar al presidente del Gobierno si ya no confía en él, pero solo si a la vez propone a otro presidente. Importa porque controla al Gobierno sin dejar el país sin nadie al mando. Si no existiera, no habría forma pacífica de cambiar un Gobierno que lo hace mal. Por ejemplo, la oposición puede intentar sustituir al presidente proponiendo a otra persona.',
  117: 'El artículo 117 presenta al Poder Judicial: los jueces, que aplican las leyes y son independientes, es decir, no reciben órdenes de nadie para juzgar. La justicia se administra en nombre del pueblo. Importa porque unos jueces libres protegen a todos por igual. Si no existiera, quien mandara podría decidir quién es culpable. Por ejemplo, un juez puede dar la razón a un ciudadano frente al mismísimo Gobierno.',
  137: 'El artículo 137 explica cómo se organiza España por dentro: en municipios, que son los pueblos y ciudades, en provincias y en comunidades autónomas, y todos pueden gestionar sus propios asuntos. Importa porque acerca las decisiones a la gente. Si no existiera, todo se decidiría desde un único sitio muy lejano. Por ejemplo, tu ayuntamiento se ocupa de tu barrio sin tener que preguntar por todo al Gobierno central.',
  149: 'El artículo 149 dice qué asuntos decide solo el Estado para toda España, como la defensa, la moneda o las relaciones con otros países, para que sean iguales en todas partes. Importa porque hay cosas que deben ser comunes a todos. Si no existiera, cada zona podría tener su propio ejército o su propio dinero, y sería un caos. Por ejemplo, gracias a él usamos la misma moneda en toda España.',
  159: 'El artículo 159 presenta al Tribunal Constitucional, un tribunal especial que vigila que ninguna ley vaya en contra de la Constitución. Es como el árbitro que hace cumplir las reglas del juego. Importa porque protege la Constitución por encima de todo. Si no existiera, se podrían aprobar leyes injustas que rompieran tus derechos. Por ejemplo, puede anular una ley si comprueba que va contra la Constitución.',
  168: 'El artículo 168 habla de la reforma más difícil. Para cambiar lo más importante de la Constitución, como los derechos fundamentales o la Corona, hacen falta muchísimos acuerdos e incluso preguntar al pueblo en un referéndum. Importa porque protege lo esencial de cambios a la ligera. Si no existiera, se podrían quitar tus derechos con demasiada facilidad. Por ejemplo, tocar la parte de los derechos fundamentales exige un proceso larguísimo y tu voto.',
};

if (typeof module !== 'undefined') module.exports = { VOZ };
